# 실습 1. Numpy 핸들링 실습
- https://numpy.org/doc/stable/index.html

In [1]:
import numpy as np

## 1. Numpy array 생성과 연산
### Numpy array 만들기

In [2]:
# array 만들기
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [13]:
print(array_1d)
print(array_2d)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### numpy.ndarray.shape
- Numpy 배열의 차원을 확인합니다.
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html

In [14]:
#(아래 코드를 완성하세요.) array_1d의 차원을 확인하세요. (정답: array_1d.shape )
array_1d.____

(5,)

In [15]:
#(아래 코드를 완성하세요.) array_2d의 차원을 확인하세요. (정답: array_2d.shape )
array_2d.____

(2, 5)

### numpy.zeros
- 주어진 차원으로 0으로 채워진 배열을 생성합니다.
- https://numpy.org/doc/stable/reference/generated/numpy.zeros.html?highlight=zero


In [30]:
#(아래 코드를 완성하세요.) 5개의 0으로 채워진 1차원 배열을 생성하세요. (정답: empty_array_1d = np.zeros(5) )
empty_array_1d = np.____

print(empty_array_1d)
print(empty_array_1d.shape)

[0. 0. 0. 0. 0.]
(5,)


In [31]:
#(아래 코드를 완성하세요.) (2,5) 차원을 가지는 0으로 채워진 2차원 배열을 생성하세요. (정답: empty_array_1d = np.zeros(2,5) )
empty_array_2d = np.____

print(empty_array_2d)
print(empty_array_2d.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(2, 5)


### np.ones
- 주어진 차원으로 1로 채워진 배열을 생성합니다.
- https://numpy.org/doc/stable/reference/generated/numpy.ones.html?highlight=ones

In [10]:
#(아래 코드를 완성하세요.)  5개의 1으로 채워진 1차원 배열을 생성하세요. (정답: np.ones([5]) )
np.____([5])

array([1., 1., 1., 1., 1.])

### np.random.random
- 주어진 차원으로 0~1사이의 임의의 실수로 된 배열을 생성합니다.
- https://numpy.org/doc/stable/reference/random/index.html

In [17]:
#(아래 코드를 완성하세요.)  난수로 구성된 (2,5)차원의 배열을 생성하세요. (정답: random_array = np.random.random((2, 5)) )
random_array = np.random._____((2, 5))
random_array

array([[0.23218866, 0.15075595, 0.87516006, 0.37699325, 0.83025608],
       [0.2180551 , 0.86740679, 0.31165611, 0.7367775 , 0.36461994]])

In [35]:
# array 체크해보기
random_array.dtype

dtype('float64')

### np.ndarray.astype
- 주어진 배열의 자료형을 변경합니다.
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html?highlight=astype#numpy.ndarray.astype

In [36]:
#(아래 코드를 완성하세요.)  random_array 배열을 'float32'로 자료형을 변환하세요. (정답: random_array.astype('float32') )
random_array._____('float32')

array([[0.64027375, 0.01032324, 0.874547  , 0.8676279 , 0.416399  ],
       [0.9801275 , 0.8710709 , 0.4855941 , 0.2553211 , 0.6019728 ]],
      dtype=float32)

## 2. array의 연산
- 배열 + 스칼라 연산

In [19]:
random_array + 1

array([[1.23218866, 1.15075595, 1.87516006, 1.37699325, 1.83025608],
       [1.2180551 , 1.86740679, 1.31165611, 1.7367775 , 1.36461994]])

In [33]:
#(아래 코드를 완성하세요.) empty_array_2 d 로부터 스칼라 연산을 이용하여 1로 채워진 2차원 배열을 생성하세요. (정답: empty_array_plus_one = empty_array_2d + 1 )
empty_array_plus_one = empty_array_2d + ___

empty_array_plus_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- 배열 + 배열 연산

In [23]:
# 배열 + 배열
empty_array_plus_one + random_array

array([[1.23218866, 1.15075595, 1.87516006, 1.37699325, 1.83025608],
       [1.2180551 , 1.86740679, 1.31165611, 1.7367775 , 1.36461994]])

- 논리연산

In [39]:
empty_array_plus_one == empty_array_plus_one

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
empty_array_plus_one == random_array

array([[False, False, False, False, False],
       [False, False, False, False, False]])

- 수학연산 : 거듭제곱, 삼각함수, 로그함수 등
- https://numpy.org/doc/stable/reference/generated/numpy.power.html?highlight=power#numpy.power

In [41]:
# (아래 코드를 완성하세요.) 2^10 값을 계산하세요. (정답: np.power(2, 10)  )
np.____(2, 10) 

1024

In [42]:
# (아래 코드를 완성하세요.) sin(0) 값을 계산하세요. (정답: np.sin(0)  )
np.___(0)

0.0

In [43]:
# (아래 코드를 완성하세요.) cos(0) 값을 계산하세요. (정답: np.cos(0)  )
np.___(0)

1.0

In [44]:
# (아래 코드를 완성하세요.) 자연로그 log(0) 값을 계산하세요. (정답: np.log(1)  )
np.___(1)

0.0

In [24]:
# (아래 코드를 완성하세요.) 지수함수 e^1 값을 계산하세요. (정답: np.exp(1)  )
np.___(1)

2.718281828459045

- 차원축소 연산
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sum.html?highlight=sum

In [47]:
# (아래 코드를 완성하세요.) random_array 배열의 원소의 합을 구하세요. (정답: random_array.sum())
random_array.___()

6.003257274859953

In [25]:
# (아래 코드를 완성하세요.) random_array 배열에서 최소값과 최대값을 구하세요. (정답: random_array.min(), random_array.max() )
random_array.___(), random_array.___()

(0.15075595224753002, 0.8751600593487217)

## 3. 배열의 원소 선택

In [49]:
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
# (아래 코드를 완성하세요.) 첫번째 row를 선택하세요. (정답: array_2d[0, :] )
array_2d[___, ___]

array([1, 2, 3, 4, 5])

In [51]:
# (아래 코드를 완성하세요.) 첫번째 column을 선택하세요. (정답: array_2d[:, 0] )
array_2d[___, ___]

array([1, 6])

In [52]:
# (아래 코드를 완성하세요.) 첫번째 부터 세번째 컬럼까지 모든 row를 선택하세요. (정답: array_2d[:, 0:3] )
array_2d[___, ___]

array([[1, 2, 3],
       [6, 7, 8]])

---
## 연습문제
1. 0 ~ 1 사이의 임의의 실수를 원소로 가지는 (3,4) 차원의 배열을 생성하세요.
1. 1 ~ 10사이의 임의의 정수를 원소로 가지는 (3,4) 차원의 배열을 생성하세요.
1. 0 또는 1을 원소를 랜덤하게 가지는 (5,) 차원의 배열을 생성하세요. 
1. 밑이 10인 로그함수로 x=1에 대한 로그함수값을 계산하세요.
1. 1번에서 생성한 배열의 원소의 합을 구하세요.
1. 1번에서 생성한 배열로부터 (2,1) 위치의 원소를 선택하세요.
