# 실습3. Scikit-learn
---
## 1. ML 모델개발 실습

In [75]:
import numpy as np
import pandas as pd
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

### Iris 데이터셋 예제 로드

In [76]:
# 예제: 데이터 불러오기
iris = datasets.load_iris()

In [77]:
print(type(iris))
print(iris)

<class 'sklearn.utils.Bunch'>
{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
    

In [78]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [79]:
X, y = iris.data, iris.target

In [80]:
X.shape, y.shape

((150, 4), (150,))

In [81]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [82]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 데이터셋 Split

In [83]:
# train, test 데이터 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [84]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [85]:
X_train

array([[4.4, 3. , 1.3, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [6.1, 2.9, 4.7, 1.4],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 2.7, 4.1, 1. ],
       [4.8, 3. , 1.4, 0.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.7, 3. , 5.2, 2.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.9, 1.8],
       [6.3, 2.3, 4.4, 1.3],
       [6.9, 3.1, 5.4, 2.1],
       [4.3, 3. , 1.1, 0.1],
       [5.1, 3.7, 1.5, 0.4],
       [6.2, 3.4, 5.4, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.2, 2.7, 3.9, 1.4],
       [5.8, 4. , 1.2, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [6.7, 3.3, 5.7, 2.1],
       [5.2, 3.5, 1.5, 0.2],
       [6. , 3. , 4.8, 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 3.5, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [6.5, 2.8, 4.6, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.8, 2.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 2

In [86]:
y_train

array([0, 2, 0, 0, 1, 1, 1, 0, 2, 2, 0, 1, 2, 1, 2, 0, 0, 2, 1, 1, 0, 1,
       2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 2, 2, 0, 0, 0, 1, 1, 0, 1,
       1, 2, 0, 0, 2, 1, 0, 1, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 2, 2, 2, 1,
       1, 1, 2, 2, 1, 0, 2, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 2, 0,
       0, 2, 2, 1, 0, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 0, 0, 1, 1, 1,
       1, 0])

### 머신러닝 모델 학습

- 의사결정트리 모델을 이용한 학습실행

In [87]:
# Decision Tree 를 사용하여 classification 해보기
from sklearn import tree
tree_clf = tree.DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [88]:
y_pred = tree_clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.8947368421052632

### 추론 결과확인

In [89]:
y_pred

array([0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2, 0, 1, 2, 1,
       2, 0, 1, 2, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 2, 0])

In [90]:
y_test

array([0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2, 0, 1, 2, 2,
       2, 0, 1, 2, 1, 0, 0, 2, 0, 1, 0, 0, 2, 2, 2, 0])

- Confustion Maxtrix

In [91]:
pd.crosstab(y_test, y_pred, rownames=['real'], colnames=['pred'])

pred   0   1   2
real            
0     13   0   0
1      0  11   1
2      0   3  10

### 다른 ML 알고리즘 적용

In [92]:
# SVM (support vector machine) 을 사용하여 classification 해보기
from sklearn import svm
svm_clf = svm.SVC()
svm_clf.fit(X_train, y_train)
y_pred = svm_clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.9210526315789473

In [93]:
pd.crosstab(y_test, y_pred, rownames=['real'], colnames=['pred'])

pred   0   1   2
real            
0     13   0   0
1      0  11   1
2      0   2  11

---
## 2. Scikit-learn의 유틸리티들

### 데이터셋 Split

In [94]:
# train, test 데이터 나누기
X_train, X_test, y_train, y_test = train_test_split(X, y)

# 데이터건수 확인
print(len(X_train), len(X_test), len(y_train), len(y_test))

112 38 112 38


In [95]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

# 데이터건수 확인
print(len(X_train), len(X_test), len(y_train), len(y_test))

120 30 120 30


In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

# 데이터건수 확인
print(len(X_train), len(X_test), len(y_train), len(y_test))

135 15 135 15


- 반복수행시에도 동일한 결과를 리턴하도록 random_seed 설정

In [97]:
random_seed = 0
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = random_seed)

# 데이터건수 확인
print(len(X_train), len(X_test), len(y_train), len(y_test))

112 38 112 38


### Scaler

In [98]:
X_train[:10]

array([[5.9, 3. , 4.2, 1.5],
       [5.8, 2.6, 4. , 1.2],
       [6.8, 3. , 5.5, 2.1],
       [4.7, 3.2, 1.3, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [5. , 3.5, 1.6, 0.6],
       [5.4, 3.7, 1.5, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5]])

- StandardScaler : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [99]:
from sklearn.preprocessing import StandardScaler
scaler1 = StandardScaler().fit(X_train)
X1 = scaler1.transform(X_train)
X1[:10]

array([[ 0.01543995, -0.11925475,  0.22512685,  0.35579762],
       [-0.09984503, -1.04039491,  0.11355956, -0.02984109],
       [ 1.05300481, -0.11925475,  0.95031423,  1.12707506],
       [-1.36797986,  0.34131533, -1.39259884, -1.31530348],
       [ 1.1682898 ,  0.11103029,  0.72717965,  1.38416753],
       [-1.0221249 ,  1.03217045, -1.2252479 , -0.80111852],
       [-0.56098497,  1.49274053, -1.28103155, -1.31530348],
       [-1.0221249 , -2.42210516, -0.16535866, -0.28693357],
       [ 0.70714986, -0.11925475,  0.95031423,  0.74143634],
       [ 0.93771983,  0.57160037,  1.06188152,  1.64126001]])

- MinMaxScaler : https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html?highlight=minmax#sklearn.preprocessing.MinMaxScaler

In [100]:
from sklearn.preprocessing import MinMaxScaler
scaler2 = MinMaxScaler().fit(X_train)
X2 = scaler2.transform(X_train)
X2[:10]

array([[0.44444444, 0.41666667, 0.53448276, 0.58333333],
       [0.41666667, 0.25      , 0.5       , 0.45833333],
       [0.69444444, 0.41666667, 0.75862069, 0.83333333],
       [0.11111111, 0.5       , 0.03448276, 0.04166667],
       [0.72222222, 0.45833333, 0.68965517, 0.91666667],
       [0.19444444, 0.625     , 0.0862069 , 0.20833333],
       [0.30555556, 0.70833333, 0.06896552, 0.04166667],
       [0.19444444, 0.        , 0.4137931 , 0.375     ],
       [0.61111111, 0.41666667, 0.75862069, 0.70833333],
       [0.66666667, 0.54166667, 0.79310345, 1.        ]])

### OneHotEncoder
- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder

In [101]:
df = pd.DataFrame([ [2,1,'male','A',3],
                    [3,2,'female','C',5],
                    [3,4,'male','B',7],
                    [5,5,'female','A',10],
                    [7,5,'female','B',12],
                    [2,5,'male','A',7],
                    [9,2,'male','C',13]
], columns=['hours', 'attendance', 'sex', 'cate', 'score'])
df

hours  attendance     sex cate  score
0      2           1    male    A      3
1      3           2  female    C      5
2      3           4    male    B      7
3      5           5  female    A     10
4      7           5  female    B     12
5      2           5    male    A      7
6      9           2    male    C     13

- 원핫인코딩

In [102]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
ohe.fit(df[['sex']])
ohe.transform(df[['sex']])

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [103]:
ohe.fit(df[['cate']])
ohe.transform(df[['cate']])

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

### LabelEncoder
- https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html?highlight=labelencoder#sklearn.preprocessing.LabelEncoder

In [104]:
from sklearn.preprocessing import LabelEncoder
lbe = LabelEncoder()
lbe.fit(df['sex'])
lbe.transform(df['sex'])

array([1, 0, 1, 0, 0, 1, 1])

In [105]:
lbe = LabelEncoder()
lbe.fit(df['cate'])
lbe.transform(df['cate'])

array([0, 2, 1, 0, 1, 0, 2])

### Make_column_transformer
- https://scikit-learn.org/stable/modules/generated/sklearn.compose.make_column_transformer.html

In [106]:
X = pd.DataFrame ({'city': ['London', 'London', 'Paris', 'Sallisaw'],
                   'rating1': [5, 3, 4, 5],
                   'rating2': [4, 5, 4, 3]})
X

city  rating1  rating2
0    London        5        4
1    London        3        5
2     Paris        4        4
3  Sallisaw        5        3

In [107]:
from sklearn.compose import make_column_transformer
column_trans = make_column_transformer( (OneHotEncoder(), ['city']),
                                        (StandardScaler(), ['rating1']),
                                        remainder=MinMaxScaler())

In [108]:
column_trans.fit_transform(X)

array([[ 1.        ,  0.        ,  0.        ,  0.90453403,  0.5       ],
       [ 1.        ,  0.        ,  0.        , -1.50755672,  1.        ],
       [ 0.        ,  1.        ,  0.        , -0.30151134,  0.5       ],
       [ 0.        ,  0.        ,  1.        ,  0.90453403,  0.        ]])

### SimpleImputer
- https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer

In [109]:
from sklearn.impute import SimpleImputer

# strategy = “median”, “most_frequent”, “constant” 등 사용가능
imp = SimpleImputer(missing_values=np.nan, strategy='mean') 
X1 = [[1, 2], [np.nan, 3], [7, 6]]
imp.fit(X1)

SimpleImputer()

In [110]:
X2 = [[np.nan, 2], [6, np.nan], [7, 6]]
imp.transform(X2)

array([[4.        , 2.        ],
       [6.        , 3.66666667],
       [7.        , 6.        ]])

- X1의 컬럼별 평균값을 이용하여 Impute 실행된 것 확인

In [111]:
pd.DataFrame(X1).mean()

0    4.000000
1    3.666667
dtype: float64

### IterativeImputer
- https://scikit-learn.org/stable/modules/generated/sklearn.impute.IterativeImputer.html#sklearn.impute.IterativeImputer

In [112]:
from sklearn.experimental import enable_iterative_imputer  
from sklearn.impute import IterativeImputer

imp = IterativeImputer()
X1 = [[1, 2], [3, 6], [4, 8], [np.nan, 3], [7, np.nan]]
imp.fit(X1)

IterativeImputer()

- 두 컬럼간 correlation정보를 반영하여 regression 기반으로 Impute 실행

In [113]:
X2 = [[np.nan, 2], [6, np.nan], [np.nan, 6], [np.nan, 100]]
imp.transform(X2)

array([[  1.00007297,   2.        ],
       [  6.        ,  12.00002754],
       [  2.99996145,   6.        ],
       [ 49.99734056, 100.        ]])

### KNNImputer
- https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html?highlight=knnimputer#sklearn.impute.KNNImputer

In [114]:
from sklearn.impute import KNNImputer

X1 = [[1, 2, 3], [3, 6, 8], [np.nan, 7, 7], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(X1)

array([[1. , 2. , 3. ],
       [3. , 6. , 8. ],
       [5.5, 7. , 7. ],
       [8. , 8. , 7. ]])

### PCA를 이용한 차원축소

In [117]:
# Unsupersised Algorithm: PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
transformed_X = pca.fit_transform(iris.data)

In [118]:
iris.data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [119]:
transformed_X[:10]

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425]])